version: 2.0
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: mvn clean install 
      - persist_to_workspace:
         root: ./
         paths:
           - target/surefire-reports

  test:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: mvn clean install
  Deploy:
    docker:
      - image: 'cimg/python:3.6'
       
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: surefire-reports
          to: 's3://deployaws17'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: surefire-reports
          to: 's3://deployaws17'
      
workflows:
  version: 2

  build-then-test-then-Deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - Deploy:
          requires:
            - test
            
             