orbs:
  maven: circleci/maven@1.3.0
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test:
          command: 
            -npm install -g selenium-webdriver@3.5.0
            -X verify

